5ый номер

In [45]:
import numpy as np
P=np.array([[0,-1/27,-8/27],[-8/25,0,-8/25],[-3/23,-2/23,0]])
c=np.array([[4/27],[1/5],[4/23]])
x_curr = np.array([[0],[0],[0]])
for i in range(1,50):
    x_new = P@x_curr+c
    if(np.absolute(x_new-x_curr)<=0.01).all():
        print(i)
        print(x_curr)
        break
    x_curr = x_new

5
[[0.09783974]
 [0.11751881]
 [0.1492688 ]]


In [43]:
P=np.array([[0,-1/27,-8/27],[-8/25,0,-8/25],[-3/23,-2/23,0]])
c=np.array([[4/27],[1/5],[4/23]])
x_curr_50 = np.array([[0],[0],[0]])
for i in range(1,50):
    x_new = P@x_curr_50+c
    x_curr_50 = x_new

In [44]:
x_curr_50

array([[0.09909412],
       [0.12011617],
       [0.15054284]])

In [46]:
# ошибка между 50-ой и 5-ой итерацией
print(np.absolute(x_curr_50-x_curr))

[[0.00125437]
 [0.00259736]
 [0.00127404]]


6ой номер

In [47]:
P=np.array([[1/4,1/4,0,1/4,0],[0,0,1/3,1/4,0],[1/4,1/4,1/3,1/4,0],[1/4,1/4,1/3,0,0],[1/4,1/4,0,1/4,1]])

In [50]:
alpha = 0.85
beta = 0.15
Q = alpha*P + 0.15/5*np.ones((5,5))
Q

array([[0.2425    , 0.2425    , 0.03      , 0.2425    , 0.03      ],
       [0.03      , 0.03      , 0.31333333, 0.2425    , 0.03      ],
       [0.2425    , 0.2425    , 0.31333333, 0.2425    , 0.03      ],
       [0.2425    , 0.2425    , 0.31333333, 0.03      , 0.03      ],
       [0.2425    , 0.2425    , 0.03      , 0.2425    , 0.88      ]])

In [54]:
x=np.ones(5)/5
for i in range(500):
    x = Q@x
print(x)
print(f"самая влиятельная вершина под номером {np.argmax(x)+1}")

[0.08937857 0.08719286 0.12471429 0.10285714 0.59585714]
самая влиятельная вершина под номером 5
